Repository depromeet/14th-team5-BE, pull requests merged in 2023-12, with the labels that each got.

#16 [OING-25] chore: NCP ObjectStorage 세팅
  build.gradle
  config/build.gradle
  config/src/main/java/com/oing/config/ObjectStorageConfig.java
  config/src/main/java/com/oing/config/properties/ObjectStorageProperties.java
  config/src/main/java/com/oing/config/properties/WebProperties.java
  config/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  config/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  config/src/main/resources/application.yaml
  config/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
  config/src/test/java/com/oing/support/InfraTest.java
  config/src/test/resources/application.yaml
Labels: ✨ FEATURE, ⚙️ CHORE

#20 [OING-46] feat: Member, Post 모듈 추가하기
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  config/build.gradle
  family/build.gradle
  post/build.gradle
  settings.gradle
Labels: ✨ FEATURE

#19 [OING-32] refactor: S3 PresignedUrl 로직 리팩터링
  README.md
  build.gradle
  common/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  common/src/main/java/com/oing/util/PreSignedUrlGenerator.java
  config/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  config/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  config/src/main/resources/template-application-local.yaml
  config/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
Labels: ♻️ REFACTORING

#21 [OING-50] refactor: Config 모듈명 Gateway로 변경
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  .github/workflows/test.yaml
  gateway/build.gradle
  gateway/src/main/java/com/oing/ServerApplication.java
  gateway/src/main/java/com/oing/component/ApplicationListener.java
  gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
  gateway/src/main/java/com/oing/component/SlackGateway.java
  gateway/src/main/java/com/oing/component/UlidIdentityGenerator.java
  gateway/src/main/java/com/oing/config/ObjectStorageConfig.java
  gateway/src/main/java/com/oing/config/SpringSecurityConfig.java
  gateway/src/main/java/com/oing/config/SpringWebConfig.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/config/SwaggerConfig.java
  gateway/src/main/java/com/oing/config/authentication/APIKeyAuthentication.java
  gateway/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  gateway/src/main/java/com/oing/config/properties/ExternalUrlProperties.java
  gateway/src/main/java/com/oing/config/properties/ObjectStorageProperties.java
  gateway/src/main/java/com/oing/config/properties/TokenExpirationProperties.java
  gateway/src/main/java/com/oing/config/properties/TokenProperties.java
  gateway/src/main/java/com/oing/config/properties/WebHeaderNameProperties.java
  gateway/src/main/java/com/oing/config/properties/WebProperties.java
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  gateway/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application-test.yaml
  gateway/src/main/resources/application.yaml
  gateway/src/main/resources/template-application-local.yaml
  gateway/src/test/java/com/oing/ServerApplicationTests.java
  gateway/src/test/java/com/oing/component/ApplicationListenerTest.java
  gateway/src/test/java/com/oing/component/JWTTokenGeneratorTest.java
  gateway/src/test/java/com/oing/component/UlidIdentityGeneratorTest.java
  gateway/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
  gateway/src/test/java/com/oing/support/InfraTest.java
  gateway/src/test/resources/application.yaml
  settings.gradle
Labels: ♻️ REFACTORING

#24 [OING-33] feat: DDL 작성 및 flyway 활성화
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/db/migration/V1__init.sql
  gateway/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
Labels: ✨ FEATURE

#27 [OING-57] hotfix: Member 도메인 entity & repository 구성 오타
  common/src/main/java/com/oing/domain/model/BaseAuditEntity.java
Labels: 🔥 HOTFIX

#23 [OING-40] feat: Feed부분 API 설계하기
  common/src/main/java/com/oing/domain/PaginationDTO.java
  common/src/main/java/com/oing/dto/response/ArrayResponse.java
  common/src/main/java/com/oing/dto/response/PaginationResponse.java
  common/src/test/java/com/oing/domain/PaginationDTOTest.java
  common/src/test/java/com/oing/dto/response/ArrayResponseTest.java
  common/src/test/java/com/oing/dto/response/PaginationResponseTest.java
  member/src/main/java/com/oing/dto/response/MemberResponse.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  post/src/main/java/com/oing/controller/PostFeedController.java
  post/src/main/java/com/oing/dto/response/PostFeedResponse.java
  post/src/main/java/com/oing/restapi/PostFeedApi.java
  post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java
Labels: ✨ FEATURE, 🔒 HOLD

#28 [OING-58] feat: MemberPost 도메인 entity & repository 구성
  member/src/test/java/com/oing/domain/model/MemberTest.java
  member/src/test/java/com/oing/domain/model/SocialMemberTest.java
  post/src/main/java/com/oing/domain/model/MemberPost.java
  post/src/main/java/com/oing/domain/model/MemberPostComment.java
  post/src/main/java/com/oing/domain/model/MemberPostReaction.java
  post/src/main/java/com/oing/repository/MemberPostCommentRepository.java
  post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
  post/src/main/java/com/oing/repository/MemberPostRepository.java
  post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
  post/src/test/java/com/oing/domain/model/MemberPostTest.java
Labels: ✨ FEATURE

#33 [OING-40] feature: API 경로 변경 및 Response DTO 변경
  common/src/main/java/com/oing/dto/response/PaginationResponse.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE

#29 [OING-62] feat: 가족 구성원 Profile 조회 API 설계
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/test/java/com/oing/dto/response/FamilyMemberProfileResponseTest.java
Labels: ✨ FEATURE, 🔒 HOLD

#32 [Suggestion] chore: PR 작성 자동화
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr.yaml
Labels: 🔒 HOLD, ⚙️ CHORE

#31 [OING-56] feat: Family 모듈 구성
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/domain/Family.java
  family/src/main/java/com/oing/repository/FamilyRepository.java
  family/src/main/java/com/oing/restapi/FamilyApi.java
  family/src/main/java/com/oing/service/FamilyService.java
Labels: ✨ FEATURE

#30 [OING-41] feat: 금일 피드 업로드 여부 조회 API 추가
  .gitignore
  common/src/main/java/com/oing/util/AuthenticationHolder.java
  family/src/main/java/com/oing/domain/model/Family.java
  family/src/main/java/com/oing/repository/FamilyRepository.java
  gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
  gateway/src/main/java/com/oing/component/TokenAuthenticationHolder.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  gateway/src/test/java/com/oing/component/JWTTokenGeneratorTest.java
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
  member/src/main/java/com/oing/dto/response/MemberResponse.java
  member/src/main/java/com/oing/exception/TokenNotValidException.java
  member/src/main/java/com/oing/service/TokenGenerator.java
  member/src/test/java/com/oing/domain/exception/TokenNotValidExceptionTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE

#35 [OING-66] feat: PresignedUrl 요청 API 구현
  common/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  gateway/src/test/java/com/oing/component/JWTTokenGeneratorTest.java
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/controller/MemberController.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE

#34 [OING-63] feat: 1차 와이어프레임 API 설계
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/dto/response/FamilyInvitationLinkResponse.java
  family/src/main/java/com/oing/dto/response/FamilyMonthlyStatisticsResponse.java
  family/src/main/java/com/oing/dto/response/FamilyResponse.java
  family/src/main/java/com/oing/restapi/FamilyApi.java
  gateway/src/main/java/com/oing/config/SwaggerConfig.java
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/dto/request/UpdateMemberRequest.java
  member/src/main/java/com/oing/restapi/AuthApi.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  post/src/main/java/com/oing/controller/CalendarController.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/controller/PostReactionController.java
  post/src/main/java/com/oing/dto/request/CreatePostReactionRequest.java
  post/src/main/java/com/oing/dto/request/CreatePostRequest.java
  post/src/main/java/com/oing/dto/response/CalendarResponse.java
  post/src/main/java/com/oing/dto/response/PostResponse.java
  post/src/main/java/com/oing/restapi/CalendarApi.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/restapi/PostReactionApi.java
  post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java
Labels: ✨ FEATURE

#37 [OING-73] feat: family, post api mock 구현
  family/src/main/java/com/oing/controller/FamilyController.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE

#38 [OING-71] feat: 회원정보 수정 API 모킹
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/dto/request/UpdateMemberRequest.java
  member/src/main/java/com/oing/restapi/MemberApi.java
Labels: ✨ FEATURE

#36 [OING-67] feat: 피드 업로드 API 모킹
  common/src/main/java/com/oing/util/PreSignedUrlGenerator.java
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  gateway/src/main/resources/db/migration/V2__modify_Post.sql
  gateway/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
  member/src/test/java/com/oing/domain/CreateNewUserDTOTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/domain/model/MemberPost.java
  post/src/main/java/com/oing/domain/model/MemberPostReaction.java
  post/src/main/java/com/oing/dto/request/CreatePostRequest.java
  post/src/main/java/com/oing/dto/response/PostResponse.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
  post/src/test/java/com/oing/domain/model/MemberPostTest.java
  post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java
Labels: ✨ FEATURE

#40 [OING-68] feat: Post Reaction API 모킹
  post/src/main/java/com/oing/controller/PostReactionController.java
  post/src/main/java/com/oing/dto/request/CreatePostReactionRequest.java
  post/src/main/java/com/oing/dto/request/PostReactionRequest.java
  post/src/main/java/com/oing/restapi/PostReactionApi.java
Labels: ✨ FEATURE

#41 [OING-83] 회원 탈퇴 API 모킹
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/restapi/MemberApi.java
Labels: ✨ FEATURE

#43 [OING-88] feat: Emoji Enum 타입으로 변경
  post/src/main/java/com/oing/controller/PostReactionController.java
  post/src/main/java/com/oing/domain/Emoji.java
  post/src/main/java/com/oing/domain/model/MemberPostReaction.java
  post/src/main/java/com/oing/dto/request/PostReactionRequest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
Labels: ✨ FEATURE

#42 [OING-84] feat: Widget API 구현
  .github/workflows/pr.yaml
  build.gradle
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  common/src/main/java/com/oing/util/OptimizedImageUrlGenerator.java
  gateway/src/main/java/com/oing/component/TokenAuthenticationHolder.java
  gateway/src/main/java/com/oing/config/QuerydslConfig.java
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/controller/WidgetController.java
  gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/java/com/oing/restapi/WidgetApi.java
  gateway/src/main/resources/application.yaml
  gateway/src/test/resources/application.yaml
  member/src/main/java/com/oing/exception/MemberNotFoundException.java
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/service/MemberService.java
  post/src/main/java/com/oing/controller/CalendarController.java
  post/src/main/java/com/oing/domain/MemberPostCountDTO.java
  post/src/main/java/com/oing/dto/response/CalendarResponse.java
  post/src/main/java/com/oing/repository/MemberPostRepository.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE

#39 [OING-70] feat: Calendar API 구현
  gateway/src/main/java/com/oing/controller/CalendarController.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: ✨ FEATURE

#44 [OING-90] hotfix: MemberService 및 WidgetController에서의 컴파일 에러
  gateway/src/main/java/com/oing/controller/CalendarController.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: 🔥 HOTFIX

#45 [OING-75] feat: Post 작성 API 구현
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/domain/model/MemberPost.java
  post/src/main/java/com/oing/dto/request/CreatePostRequest.java
  post/src/main/java/com/oing/exception/InvalidUploadTimeException.java
  post/src/main/java/com/oing/repository/MemberPostRepository.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE

#47 [OING-79] feat: 멤버 닉네임/프로필 이미지 수정 API 구현
  common/src/main/java/com/oing/dto/request/PreSignedUrlRequest.java
  common/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  common/src/main/java/com/oing/util/PreSignedUrlGenerator.java
  gateway/src/main/java/com/oing/config/AsyncConfig.java
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/model/Member.java
  member/src/main/java/com/oing/dto/request/CreateNewMemberRequest.java
  member/src/main/java/com/oing/dto/request/UpdateMemberNameRequest.java
  member/src/main/java/com/oing/dto/request/UpdateMemberProfileImageUrlRequest.java
  member/src/main/java/com/oing/dto/request/UpdateMemberRequest.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/request/CreatePostRequest.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE

#50 [OING-77] feat: Post 조회 관련 API 구현
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/response/PostResponse.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE

#49 [OING-81] feat: v1/families 관련 API 구현
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  common/src/main/java/com/oing/util/RandomStringGenerator.java
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/domain/model/Family.java
  family/src/main/java/com/oing/domain/model/FamilyInviteLink.java
  family/src/main/java/com/oing/dto/response/FamilyResponse.java
  family/src/main/java/com/oing/exception/FamilyNotFoundException.java
  family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
  family/src/main/java/com/oing/service/FamilyInviteLinkService.java
  family/src/main/java/com/oing/service/FamilyService.java
  gateway/src/main/resources/db/migration/V3__create_FamilyInviteLink.sql
Labels: ✨ FEATURE

#46 [OING-80] feat: 멤버 정보 조회 관련 및 가족 그룹 생성일 조회 API 구현
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/exception/FamilyNotFoundException.java
  family/src/main/java/com/oing/restapi/FamilyApi.java
  family/src/main/java/com/oing/service/FamilyService.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: ✨ FEATURE

#54 [OING-97] CalendarApi와 관련된 에러와 잘못된 설정 해결
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
Labels: 🔥 HOTFIX, 🐛 BUG, ⚙️ CHORE

#55 [OING-98] feat: 회원 프로필 이미지 수정 기능에서 기존 이미지 삭제 로직 주석처리
  member/src/main/java/com/oing/controller/MemberController.java
Labels: ✨ FEATURE

#56 [OING-97] PR54로 구현한 티켓의 런타입 에러 해결을 위한 핫픽스...
  gateway/src/main/java/com/oing/controller/CalendarController.java
  post/src/main/java/com/oing/domain/MemberPostCountDTO.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
Labels: 🔥 HOTFIX, 🐛 BUG

#57 [OING-97] PR54 힛픽스 2
  post/src/main/java/com/oing/domain/MemberPostCountDTO.java
Labels: 🔥 HOTFIX, 🐛 BUG

#48 [OING-76] feat: Post에 대한 반응 생성/삭제 구현
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  post/src/main/java/com/oing/controller/PostReactionController.java
  post/src/main/java/com/oing/domain/model/MemberPost.java
  post/src/main/java/com/oing/exception/EmojiAlreadyExistsException.java
  post/src/main/java/com/oing/exception/EmojiNotFoundException.java
  post/src/main/java/com/oing/exception/PostNotFoundException.java
  post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
  post/src/main/java/com/oing/service/MemberPostService.java
  post/src/main/java/com/oing/service/PostReactionService.java
Labels: ✨ FEATURE

#51 [OING-94] fix: createPost 코드 개선
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  member/src/main/java/com/oing/dto/request/CreateNewMemberRequest.java
  member/src/main/java/com/oing/dto/request/UpdateMemberProfileImageUrlRequest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/request/CreatePostRequest.java
  post/src/main/java/com/oing/dto/response/PostResponse.java
  post/src/main/java/com/oing/exception/DuplicatePostUploadException.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ♻️ REFACTORING

#52 [OING-95] feat: 카카오 인증(로그인) 기능 구현
  member/src/main/java/com/oing/domain/SocialLoginProvider.java
  member/src/main/java/com/oing/dto/response/KakaoAuthResponse.java
  member/src/main/java/com/oing/service/AuthService.java
Labels: ✨ FEATURE

#58 [OING-92] feat: 회원 탈퇴 API 구현
  common/src/main/java/com/oing/domain/model/DeletableBaseAuditEntity.java
  common/src/main/java/com/oing/exception/AuthorizationFailedException.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/model/Member.java
  member/src/main/java/com/oing/repository/SocialMemberRepository.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/main/java/com/oing/service/MemberService.java
  member/src/test/java/com/oing/domain/SocialLoginProviderTest.java
Labels: ✨ FEATURE

#59 [OING-100] feat: 내 정보 조회 API & MemberResponse 누락필드 추가
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/restapi/MeApi.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/dto/response/MemberResponse.java
Labels: ✨ FEATURE

#60 [OING-101] hotfix: Post 조회시 페이지 수 카운트 이슈
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: 🔥 HOTFIX

#61 [OING-102] hotfix: Family 초대 링크 기발급 경우 기존 링크 반환
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
  family/src/main/java/com/oing/service/FamilyInviteLinkService.java
Labels: 🔥 HOTFIX, 🐛 BUG
