Repository depromeet/14th-team5-BE, pull requests merged in 2023-11, with the labels that each got.

#1 FEATURE/OING-8 -> MAIN : PR 템플릿 생성 관련
  .github/PULL_REQUEST_TEMPLATE.md
Labels: FEATURE

#2 chore: configure multi-module project structure
  build.gradle
  config/build.gradle
  config/src/main/java/com/oing/ServerApplication.java
  config/src/main/resources/application.yaml
  config/src/test/java/com/oing/ServerApplicationTests.java
  member/build.gradle
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/service/MemberService.java
  settings.gradle
  src/main/resources/application.yml
Labels: FEATURE

#3 [OING-7] chore: CI 파이프라인 추가
  .github/workflows/build.yaml
  .github/workflows/deploy.yaml
  .github/workflows/prod.yaml
  config/build.gradle
  config/src/main/resources/application-prod.yaml
Labels: 📌 FEATURE

#6 [OINT-19] feature: 스프링 시큐리티 설정
  config/src/main/java/com/oing/ServerApplication.java
  config/src/main/java/com/oing/config/SpringSecurityConfig.java
  config/src/main/java/com/oing/config/SpringWebConfig.java
  config/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  config/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
  config/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
  config/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  config/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  config/src/main/java/com/oing/config/properties/WebHeaderNameProperties.java
  config/src/main/java/com/oing/config/properties/WebProperties.java
  config/src/main/resources/application.yaml
  settings.gradle
Labels: ✨ FEATURE

#7 [OING-10] chore: code coverage를 위한 Jacoco 설정
  build.gradle
  config/build.gradle
Labels: ⚙️ CHORE

#8 [OING-23] chore: Jacoco 테스트 커버리지 범위에서 config 모듈 제외
  build.gradle
Labels: ⚙️ CHORE

#10 [OING-24] chore: Swagger 환경 세팅
  config/src/main/java/com/oing/config/SpringWebConfig.java
  config/src/main/java/com/oing/config/SwaggerConfig.java
  config/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  config/src/main/resources/application.yaml
Labels: 📄 DOCS, ⚙️ CHORE

#9 [OING-20] feat: JWT 토큰 관리 컴포넌트 생성
  config/build.gradle
  config/src/main/java/com/oing/config/JWTTokenGenerator.java
  config/src/main/java/com/oing/config/authentication/APIKeyAuthentication.java
  config/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  config/src/main/java/com/oing/config/properties/TokenExpirationProperties.java
  config/src/main/java/com/oing/config/properties/TokenProperties.java
  config/src/main/resources/application.yaml
  member/src/main/java/com/oing/domain/TokenPair.java
  member/src/main/java/com/oing/domain/exception/TokenNotValidException.java
  member/src/main/java/com/oing/service/TokenGenerator.java
  member/src/test/java/com/oing/domain/TokenPairTest.java
  member/src/test/java/com/oing/domain/exception/TokenNotValidExceptionTest.java
Labels: ✨ FEATURE

#15 [OING-26] chore: CI/CD 파이프라인 워크플로우 개선
  .github/workflows/deploy.yaml
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  .github/workflows/test.yaml
  build.gradle
  config/build.gradle
Labels: ⚙️ CHORE
