Repository depromeet/14th-team5-BE, pull requests merged in 2024-04, with the labels that each got.

#224 [OING-298] refactor: Error message 한글로 번역
  common/src/main/java/com/oing/exception/ErrorCode.java
Labels: ♻️ REFACTORING, 우선순위_3

#222 [OING-300] feat: 콕 찌르기 API 구현
  common/src/main/java/com/oing/exception/ErrorCode.java
  common/src/main/java/com/oing/service/PostBridge.java
  gateway/src/main/resources/db/migration/V202404021150__create_memberPick_table.sql
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/MemberPick.java
  member/src/main/java/com/oing/exception/AlreadyPickedMemberException.java
  member/src/main/java/com/oing/exception/PickFailedAlreadyUploadedException.java
  member/src/main/java/com/oing/repository/MemberPickRepository.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/main/java/com/oing/service/MemberPickService.java
  post/src/main/java/com/oing/service/PostBridgeImpl.java
Labels: ✨ FEATURE, 우선순위_2

#223 [OING-289] refactor: Member 모듈의 안티패턴과 짜잘한 부분 리팩토링
  common/src/main/java/com/oing/exception/AuthorizationFailedException.java
  common/src/main/java/com/oing/exception/ErrorCode.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/controller/WidgetController.java
  gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  gateway/src/test/java/com/oing/controller/WidgetControllerTest.java
  gateway/src/test/java/com/oing/restapi/MemberApiTest.java
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/Member.java
  member/src/main/java/com/oing/exception/InvalidMemberNameLengthException.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/main/java/com/oing/service/MemberDeviceService.java
  member/src/main/java/com/oing/service/MemberQuitReasonService.java
  member/src/main/java/com/oing/service/MemberService.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
  member/src/test/java/com/oing/service/MemberServiceTest.java
Labels: ♻️ REFACTORING, ✅ TEST, 우선순위_2

#225 [OING-305] feature: Mission 도입에 맞춰 Post 테이블 변경
  gateway/src/main/resources/db/migration/V202404061645__add_mission_column_in_Post.sql
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  post/src/main/java/com/oing/domain/Post.java
  post/src/main/java/com/oing/domain/Type.java
  post/src/test/java/com/oing/domain/model/PostCommentTest.java
  post/src/test/java/com/oing/domain/model/PostReactionTest.java
  post/src/test/java/com/oing/domain/model/PostTest.java
Labels: ✨ FEATURE, 우선순위_2

#226 [OING-306] hotfix: Type Enum 필드에 enumerated 추가
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  post/src/main/java/com/oing/domain/Post.java
Labels: 🔥 HOTFIX, 🐛 BUG

#228 [OING-302] feature: 미션 포스트 작성/조회 모킹 API 추가
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/controller/WidgetControllerTest.java
  gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  gateway/src/test/java/com/oing/restapi/CommentApiTest.java
  gateway/src/test/java/com/oing/restapi/PostApiTest.java
  gateway/src/test/java/com/oing/restapi/ReactionApiTest.java
  gateway/src/test/java/com/oing/restapi/RealEmojiApiTest.java
  gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/domain/Post.java
  post/src/main/java/com/oing/domain/PostType.java
  post/src/main/java/com/oing/dto/response/PostResponse.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/service/PostService.java
  post/src/test/java/com/oing/controller/PostCommentControllerTest.java
  post/src/test/java/com/oing/controller/ReactionControllerTest.java
  post/src/test/java/com/oing/controller/RealEmojiControllerTest.java
  post/src/test/java/com/oing/domain/model/PostCommentTest.java
  post/src/test/java/com/oing/domain/model/PostReactionTest.java
  post/src/test/java/com/oing/domain/model/PostTest.java
  post/src/test/java/com/oing/dto/response/PostFeedResponseTest.java
  post/src/test/java/com/oing/service/CommentServiceTest.java
  post/src/test/java/com/oing/service/ReactionServiceTest.java
  post/src/test/java/com/oing/service/RealEmojiServiceTest.java
Labels: ✨ FEATURE, 우선순위_3

#229 [OING-303] feature: 생존신고 업로드 가능 시간 변경
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, 우선순위_3

#230 [OING-307] feat: Mission 모듈 추가
  .gitignore
  common/src/main/java/com/oing/exception/ErrorCode.java
  gateway/build.gradle
  gateway/src/main/resources/db/migration/V202404152221__create_Mission_module_tables.sql
  mission/build.gradle
  mission/src/main/java/com/oing/domain/DailyMissionHistory.java
  mission/src/main/java/com/oing/domain/Mission.java
  mission/src/main/java/com/oing/dto/request/CreateMissionRequest.java
  mission/src/main/java/com/oing/dto/request/UpdateMissionRequest.java
  mission/src/main/java/com/oing/dto/response/DailyMissionHistoryResponse.java
  mission/src/main/java/com/oing/dto/response/MissionResponse.java
  mission/src/main/java/com/oing/exception/DailyMissionHistoryNotFoundException.java
  mission/src/main/java/com/oing/exception/MissionNotFoundException.java
  mission/src/main/java/com/oing/repository/DailyMissionHistoryRepository.java
  mission/src/main/java/com/oing/repository/MissionRepository.java
  mission/src/main/java/com/oing/service/DailyMissionHistoryService.java
  mission/src/main/java/com/oing/service/MissionService.java
  post/src/main/java/com/.DS_Store
  settings.gradle
Labels: ✨ FEATURE, 우선순위_1

#233 [OING-312] fix: OING-307 티켓의 미션 모듈 엔티티들의 테이블 추가 flyway db.migration 중 발생한 에러 해결
  gateway/src/main/resources/db/migration/V202404152221__create_Mission_module_tables.sql
Labels: 🔥 HOTFIX, 🐛 BUG, 🚀 RELEASE, 우선순위_1

#232 [OING-309] feat: Mission, DailyMissionHistory의 API Mocking과 Service feature Mocking
  common/src/main/java/com/oing/service/MissionBridge.java
  gateway/src/main/java/com/oing/service/MissionBridgeImpl.java
  mission/src/main/java/com/oing/controller/MissionController.java
  mission/src/main/java/com/oing/domain/DailyMissionHistory.java
  mission/src/main/java/com/oing/dto/response/DailyMissionResponse.java
  mission/src/main/java/com/oing/restapi/MissionApi.java
  mission/src/main/java/com/oing/service/DailyMissionHistoryService.java
  mission/src/main/java/com/oing/service/MissionService.java
Labels: ✨ FEATURE, 우선순위_1

#231 [OING-308] feat: 가족구성원 랭킹 API 모킹
  gateway/src/main/java/com/oing/controller/HomeController.java
  gateway/src/main/java/com/oing/dto/response/FamilyMemberMonthlyRankingResponse.java
  gateway/src/main/java/com/oing/dto/response/FamilyMemberRankerResponse.java
  gateway/src/main/java/com/oing/restapi/HomeApi.java
Labels: ✨ FEATURE, 우선순위_1

#234 [OING-313] hotfix: 기존 post의 데이터들이 type값이 FEED로 저장되어 있는 이슈 해결
  gateway/src/main/resources/db/migration/V202404171338__set_type_column_default_value_in_Post.sql
Labels: 🔒 HOLD, 🔥 HOTFIX, 🐛 BUG, 우선순위_1

#235 [OING-314] feature: 회원 생존신고 게시글 업로드 여부 / 회원 미션 참여 가능 여부 확인 mock API 추가
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/response/MissionAvailableStatusResponse.java
  post/src/main/java/com/oing/dto/response/SurvivalUploadStatusResponse.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE, 우선순위_2

#237 [OING-311] feat: 뷰 기반 API 중 메인 페이지 API 구현
  gateway/src/main/java/com/oing/controller/ViewBasedController.java
  gateway/src/main/java/com/oing/dto/response/MainPageFeedResponse.java
  gateway/src/main/java/com/oing/dto/response/MainPagePickerResponse.java
  gateway/src/main/java/com/oing/dto/response/MainPageResponse.java
  gateway/src/main/java/com/oing/dto/response/MainPageTopBarResponse.java
  gateway/src/main/java/com/oing/restapi/ViewBasedApi.java
Labels: ✨ FEATURE, 우선순위_2

#236 [OING-315] feature: 미션 게시글 업로드/조회 API 구현 (검증 로직 제외)
  common/src/main/java/com/oing/exception/ErrorCode.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/domain/Post.java
  post/src/main/java/com/oing/exception/DuplicateMissionPostUploadException.java
  post/src/main/java/com/oing/exception/DuplicatePostUploadException.java
  post/src/main/java/com/oing/exception/DuplicateSurvivalPostUploadException.java
  post/src/main/java/com/oing/exception/MissionPostAccessDeniedFamilyException.java
  post/src/main/java/com/oing/exception/MissionPostCreateAccessDeniedMemberException.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/service/PostBridgeImpl.java
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, 우선순위_2

#238 [OING-317] refactor: 뷰 기반 API를 둘러싼 교통정리 1
  gateway/src/main/java/com/oing/controller/HomeController.java
  gateway/src/main/java/com/oing/controller/MainViewController.java
  gateway/src/main/java/com/oing/dto/response/DaytimePageResponse.java
  gateway/src/main/java/com/oing/dto/response/FamilyMemberMonthlyRankingResponse.java
  gateway/src/main/java/com/oing/dto/response/MainPageTopBarResponse.java
  gateway/src/main/java/com/oing/dto/response/NighttimePageResponse.java
  gateway/src/main/java/com/oing/restapi/HomeApi.java
  gateway/src/main/java/com/oing/restapi/MainViewApi.java
  gateway/src/main/java/com/oing/restapi/ViewBasedApi.java
Labels: 🔥 HOTFIX, ♻️ REFACTORING, 우선순위_1

#239 [OING-316] feature: 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API 구현
  gateway/src/main/java/com/oing/controller/MainViewController.java
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/PostApiTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/response/RemainingSurvivalPostCountResponse.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, 우선순위_2

#242 [OING-320] refactor: 가족 중 몇명이 더 올리면 미션 참여 가능한지 반환하는 API 로직 리팩터링
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/service/PostService.java
  post/src/test/java/com/oing/service/PostServiceTest.java
Labels: ♻️ REFACTORING, 우선순위_2

#241 [OING-319] feat: 메인 페이지에서 필요한 추가 요청받은 API 구현/모킹
  gateway/src/main/java/com/oing/controller/MainViewController.java
  gateway/src/main/java/com/oing/dto/response/DaytimePageResponse.java
  gateway/src/main/java/com/oing/dto/response/FamilyMemberMonthlyRankingResponse.java
  gateway/src/test/java/com/oing/restapi/PostApiTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/response/MissionUploadStatusResponse.java
  post/src/main/java/com/oing/dto/response/SurvivalUploadStatusResponse.java
  post/src/main/java/com/oing/restapi/PostApi.java
Labels: ✨ FEATURE, 우선순위_1

#243 [OING-322] refactor: 포스트 중복 작성 검증 로그에 today 날짜 추가
  post/src/main/java/com/oing/service/PostService.java
Labels: ♻️ REFACTORING, 우선순위_1

#245 [OING-324] refactor: NighttimeMainPage의 displayRank 필드는 늘 NULL이 되도록 수정
  gateway/src/main/java/com/oing/controller/MainViewController.java
  gateway/src/main/java/com/oing/dto/response/MainPageTopBarResponse.java
Labels: ♻️ REFACTORING, 우선순위_1

#244 [OING-323] feat: 일간 캘린더 API 추가
  common/src/main/java/com/oing/service/MemberBridge.java
  common/src/main/java/com/oing/service/MissionBridge.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/java/com/oing/service/MemberBridgeImpl.java
  gateway/src/main/java/com/oing/service/MissionBridgeImpl.java
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  mission/src/main/java/com/oing/service/MissionService.java
  post/src/main/java/com/oing/dto/response/DailyCalendarResponse.java
  post/src/main/java/com/oing/dto/response/MonthlyCalendarResponse.java
Labels: ✨ FEATURE, 우선순위_1
