Repository depromeet/14th-team5-BE, pull requests merged in 2024-03, with the labels that each got.

#190 [OING-270] feat: 회원 탈퇴 시, 프로필 이미지 키 삭제 기능 추가
  member/src/main/java/com/oing/domain/Member.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
Labels: ✨ FEATURE

#191 [OING-215] feat: AWS 프로덕션용 설정 일부 변경
  gateway/build.gradle
  gateway/src/main/java/com/oing/config/RedisConfig.java
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application.yaml
Labels: ✨ FEATURE, 우선순위_1

#189 [OING-264] feat: 어드민 대시보드 API
  gateway/src/main/java/com/oing/config/authentication/JWTTokenAuthentication.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  gateway/src/main/java/com/oing/controller/AdminController.java
  gateway/src/main/java/com/oing/domain/DateCountProjection.java
  gateway/src/main/java/com/oing/dto/response/AdminDailyDashboardResponse.java
  gateway/src/main/java/com/oing/dto/response/AdminDashboardResponse.java
  gateway/src/main/java/com/oing/dto/response/DashboardDistributionResponse.java
  gateway/src/main/java/com/oing/dto/response/DashboardValueResponse.java
  gateway/src/main/java/com/oing/repository/DashboardRepositoryCustomImpl.java
  gateway/src/main/java/com/oing/restapi/AdminApi.java
Labels: ✨ FEATURE, 우선순위_3

#192 [OING-272] chore: AWS 프로덕션용 CI/CD 파이프라인 구성
  .github/workflows/build-ecr.yaml
  .github/workflows/deploy-ecs.yaml
  .github/workflows/prod-ecs.yaml
  gateway/build.gradle
  jib.sh
Labels: ⚙️ CHORE, 우선순위_1

#194 [OING-252] feature: Sentry 로깅 고도화
  family/src/main/java/com/oing/job/FamilyStatisticJob.java
  gateway/src/main/java/com/oing/component/SentryGateway.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
Labels: ✨ FEATURE, ⚙️ CHORE, ♻️ REFACTORING

#193 [RELEASE] v1.1.9 릴리즈 업데이트
  .github/workflows/build-ecr.yaml
  .github/workflows/deploy-ecs.yaml
  .github/workflows/prod-ecs.yaml
  family/src/main/java/com/oing/job/FamilyStatisticJob.java
  gateway/build.gradle
  gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
  gateway/src/main/java/com/oing/component/SentryGateway.java
  gateway/src/main/java/com/oing/config/RedisConfig.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/config/authentication/JWTTokenAuthentication.java
  gateway/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  gateway/src/main/java/com/oing/controller/AdminController.java
  gateway/src/main/java/com/oing/domain/DateCountProjection.java
  gateway/src/main/java/com/oing/dto/response/AdminDailyDashboardResponse.java
  gateway/src/main/java/com/oing/dto/response/AdminDashboardResponse.java
  gateway/src/main/java/com/oing/dto/response/DashboardDistributionResponse.java
  gateway/src/main/java/com/oing/dto/response/DashboardValueResponse.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  gateway/src/main/java/com/oing/repository/DashboardRepositoryCustomImpl.java
  gateway/src/main/java/com/oing/restapi/AdminApi.java
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application.yaml
  gateway/src/test/java/com/oing/restapi/MemberApiTest.java
  jib.sh
  member/src/main/java/com/oing/domain/Member.java
  member/src/main/java/com/oing/exception/TokenExpiredException.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
Labels: 🚀 RELEASE

#196 [HOTFIX] chore: SENTRY_AUTH_TOKEN 추가
  .github/workflows/build-ecr.yaml
Labels: ✨ FEATURE, 🔥 HOTFIX

#197 fix: UTC로 설정된 월간 가족 이력 데이터 기록 스케줄러를 KST로 변경
  family/src/main/java/com/oing/job/FamilyStatisticJob.java
Labels: 🐛 BUG

#199 [OING-252] refactor: 잘못된 Sentry 로깅 설정 수정 및 Jwt Token 예외 핸들링 일부 리펙토링
  common/src/main/java/com/oing/exception/ErrorCode.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
  member/src/main/java/com/oing/exception/TokenExpiredException.java
  member/src/main/java/com/oing/exception/TokenNotValidException.java
Labels: 🔥 HOTFIX, ⚙️ CHORE, ♻️ REFACTORING, 우선순위_1

#200 [OING-210] fix: 가족 점수 로직 테스트 코드 추가 및 버그 해결
  family/src/main/java/com/oing/event/FamilyScoreEventListener.java
  gateway/src/test/java/com/oing/event/DatabaseCleaner.java
  gateway/src/test/java/com/oing/event/DatabaseCleanerExtension.java
  gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java
  post/src/main/java/com/oing/domain/MemberPostCommentEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostRealEmojiEntityListener.java
Labels: 🐛 BUG, ✅ TEST, 우선순위_1

#202 [OING-284] refactor: 가족 활동 점수 이벤트의 강결합 및 데드락 해결과 비동기용 테스트코드 도입
  build.gradle
  common/src/main/java/com/oing/event/MemberPostCommentCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostCommentDeletedEvent.java
  common/src/main/java/com/oing/event/MemberPostCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostDeletedEvent.java
  common/src/main/java/com/oing/event/MemberPostReactionCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostReactionDeletedEvent.java
  common/src/main/java/com/oing/event/MemberPostRealEmojiCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostRealEmojiDeletedEvent.java
  family/src/main/java/com/oing/event/FamilyScoreEventListener.java
  family/src/main/java/com/oing/repository/FamilyRepositoryCustom.java
  family/src/main/java/com/oing/repository/FamilyRepositoryCustomImpl.java
  family/src/main/java/com/oing/service/FamilyService.java
  gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java
  post/src/main/java/com/oing/domain/MemberPostCommentEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostReactionEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostRealEmojiEntityListener.java
Labels: ✨ FEATURE, ♻️ REFACTORING, 우선순위_2

#203 [OING-287] feat: iOS 딥링크 변경사항 대응
  gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java
Labels: ✨ FEATURE

#205 [OING-280] feat: 슬랙 알림 분리 및 부팅 알림 추가
  build.gradle
  gateway/src/main/java/com/oing/component/ApplicationListener.java
  gateway/src/main/java/com/oing/component/SlackGateway.java
  gateway/src/main/java/com/oing/config/properties/ExternalUrlProperties.java
  gateway/src/main/java/com/oing/event/ApplicationEventListener.java
  gateway/src/main/resources/application.yaml
Labels: ✨ FEATURE, 우선순위_2

#208 [OING-288] fix: 테스트 중 FamilyScoreEventListnerTest가 실패하는 문제 해결
  gateway/src/test/java/com/oing/event/DatabaseCleaner.java
Labels: 🐛 BUG, ✅ TEST, 우선순위_1

#211 [OING-290] refactor: CICD workflow에 잘못 주입되고 있는 환경변수 수정 및 파일 정리
  .github/workflows/PR-testcoverage-report.yaml
  .github/workflows/build.yaml
  .github/workflows/deploy.yaml
  .github/workflows/dev-base-PR-autotemplate.yaml
  .github/workflows/dev-cicd.yaml
  .github/workflows/main-base-PR-autotemplate.yaml
  .github/workflows/prod-cicd.yaml
Labels: 🐛 BUG, ⚙️ CHORE, 우선순위_1

#209 [OING-291] fix: 캘린더 API의 가족구성원 계산 로직이 삭제한 유저도 포함하는 결함을 수정
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: 🐛 BUG, 우선순위_1

#201 [OING-219] refactor: MemberPost/MemberPostRealEmoji save 로직 리팩터링
  gateway/src/main/java/com/oing/config/support/RedisLocalConfig.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/controller/MemberPostReactionController.java
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
  post/src/main/java/com/oing/service/MemberPostCommentService.java
  post/src/main/java/com/oing/service/MemberPostReactionService.java
  post/src/main/java/com/oing/service/MemberPostRealEmojiService.java
  post/src/main/java/com/oing/service/MemberPostService.java
  post/src/test/java/com/oing/controller/MemberPostControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
  post/src/test/java/com/oing/service/MemberPostRealEmojiServiceTest.java
Labels: ♻️ REFACTORING, 우선순위_3

#207 [OING-285] refactor: Family 모듈 리팩토링
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/repository/FamilyRepository.java
  family/src/main/java/com/oing/service/FamilyService.java
Labels: ♻️ REFACTORING, 우선순위_3

#213 [OING-292] fix: 중복된 로컬용 임베디드 설정 파일 삭제
  gateway/src/main/java/com/oing/config/support/RedisLocalConfig.java
Labels: 🔥 HOTFIX, 🐛 BUG, 우선순위_1

#217 [OING-297] hotfix: Post 모듈 안의 N:1 lazily initialize 에러 핫픽스
  post/src/main/java/com/oing/controller/CommentController.java
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/controller/ReactionController.java
  post/src/main/java/com/oing/controller/RealEmojiController.java
Labels: 🔥 HOTFIX, 🐛 BUG, 우선순위_1

#218 [OING-294] refactor: 캐싱 기능 및 Redis 설정 파일 삭제
  build.gradle
  gateway/src/main/java/com/oing/config/redis/EmbeddedRedisConfig.java
  gateway/src/main/java/com/oing/config/redis/RedisCacheConfig.java
  gateway/src/main/java/com/oing/config/redis/RedisConfig.java
  gateway/src/main/java/com/oing/config/redis/RedisLocalConfig.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application-test.yaml
  gateway/src/main/resources/application.yaml
  gateway/src/main/resources/template-application-local.yaml
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  gateway/src/test/java/com/oing/restapi/PostApiTest.java
  gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java
  gateway/src/test/java/com/oing/support/RedisTestConfig.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/response/CalendarResponse.java
Labels: ⚙️ CHORE, ♻️ REFACTORING, 우선순위_2
