Repository depromeet/14th-team5-BE, pull requests merged in 2024-12, with the labels that each got.

#275 [OING-375] feat: 음성 댓글 관련 API 목을 추가해요
  post/src/main/java/com/oing/controller/VoiceCommentController.java
  post/src/main/java/com/oing/domain/CommentType.java
  post/src/main/java/com/oing/dto/response/PostCommentResponseV2.java
  post/src/main/java/com/oing/restapi/VoiceCommentApi.java
Labels: ✨ FEATURE

#277 [OING-377] fix: 가족 이름 변경 도메인 로직 수정
  family/src/main/java/com/oing/domain/Family.java
Labels: 🔥 HOTFIX, 🐛 BUG

#279 [OING-381] refact: Comment, VoiceComment 및 댓글 조회 로직 리팩터링
  gateway/src/main/java/com/oing/controller/NotificationController.java
  post/src/main/java/com/oing/controller/CommentController.java
  post/src/main/java/com/oing/controller/VoiceCommentController.java
  post/src/main/java/com/oing/domain/BaseComment.java
  post/src/main/java/com/oing/domain/Comment.java
  post/src/main/java/com/oing/domain/VoiceComment.java
  post/src/main/java/com/oing/dto/response/PostCommentResponseV2.java
Labels: 🐛 BUG, ♻️ REFACTORING
