Repository depromeet/14th-team5-BE, pull requests merged in 2024-06, with the labels that each got.

#260 [OING-339] feat: 확장된 가족 초대 링크 기능을 구현하기 위한 View API Spec 우선 구현 및 응답 모킹
  family/src/main/java/com/oing/dto/response/FamilyInvitationLinkResponse.java
  family/src/main/java/com/oing/dto/response/FamilyInviteDeepLinkResponse.java
  gateway/src/main/java/com/oing/controller/FamilyInviteViewController.java
  gateway/src/main/java/com/oing/restapi/FamilyInviteViewApi.java
  gateway/src/main/java/com/oing/service/DeepLinkService.java
Labels: ✨ FEATURE, 우선순위_2

#261 [OING-337] fix: 위젯에서 미션글도 보이도록 수정 (PostRepositoryCustomImpl에서 잘못 추가된 PostType 비교절 제거)
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
Labels: ✨ FEATURE, 🐛 BUG, 우선순위_2

#262 [OING-340] feature: 가족 초대 딥링크 발급 로직 변경 및 가족 초대 뷰 기반 API 실제 로직 추가
  common/src/main/java/com/oing/service/FamilyBridge.java
  common/src/main/java/com/oing/service/MemberBridge.java
  common/src/main/java/com/oing/service/PostBridge.java
  family/src/main/java/com/oing/domain/Family.java
  family/src/main/java/com/oing/domain/FamilyInviteLink.java
  family/src/main/java/com/oing/dto/response/FamilyInviteDeepLinkResponse.java
  family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
  family/src/main/java/com/oing/service/FamilyInviteLinkService.java
  family/src/main/java/com/oing/service/FamilyService.java
  gateway/src/main/java/com/oing/controller/DeepLinkController.java
  gateway/src/main/java/com/oing/controller/FamilyInviteViewController.java
  gateway/src/main/java/com/oing/domain/DeepLink.java
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/main/java/com/oing/restapi/DeepLinkApi.java
  gateway/src/main/java/com/oing/service/DeepLinkService.java
  gateway/src/main/java/com/oing/service/FamilyBridgeImpl.java
  gateway/src/main/java/com/oing/service/MemberBridgeImpl.java
  gateway/src/main/resources/db/migration/V202406171820__add_column_to_deep_link_and_family_invite_link_tbl.sql
  gateway/src/main/resources/db/migration/V202406171920__add_family_name_column_to_family_tbl.sql
  gateway/src/test/java/com/oing/event/FamilyScoreEventListenerTest.java
  gateway/src/test/java/com/oing/repository/MemberRepositoryCustomTest.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/repository/MemberRepositoryCustom.java
  member/src/main/java/com/oing/repository/MemberRepositoryCustomImpl.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/main/java/com/oing/service/MemberService.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/service/PostBridgeImpl.java
Labels: ✨ FEATURE, 우선순위_2

#265 [OING-342] refactor: 딥링크 초대 뷰 API에서 memberId == null 인 경우 추가
  gateway/src/main/java/com/oing/controller/FamilyInviteViewController.java
Labels: ♻️ REFACTORING, 우선순위_1

#268 [OING-344] hotfix: 잘못된 위치에 있는 migration 파일 위치 변경
  gateway/src/main/resources/db/migration/V202406261718__alter_family_name_column_type.sql
Labels: 🔥 HOTFIX

#269 [OING-345] hotfix: 가족 초대 링크 잘못된 primary key 변경
  gateway/src/main/resources/db/migration/V202406291302__alter_family_invite_link_pk.sql
Labels: 🔥 HOTFIX, 🐛 BUG
