Repository depromeet/14th-team5-BE, pull requests merged in 2024-05, with the labels that each got.

#247 [OING-328] feat: DailyCalendarResponse에 PostResponse 필드 추가 (프론트 요청)
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  post/src/main/java/com/oing/dto/response/DailyCalendarResponse.java
Labels: ✨ FEATURE, 우선순위_1

#246 [OING-325] feat: 가족구성원 랭킹 API 기능 구현
  gateway/src/main/java/com/oing/controller/MainViewController.java
  gateway/src/main/java/com/oing/dto/response/FamilyMemberMonthlyRankingResponse.java
  gateway/src/main/java/com/oing/dto/response/FamilyMemberRankerResponse.java
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/restapi/MainViewApiTest.java
  gateway/src/test/java/com/oing/restapi/PostApiTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/dto/dto/PostRankerDTO.java
  post/src/main/java/com/oing/dto/response/PostRankerResponse.java
  post/src/main/java/com/oing/repository/CommentRepositoryCustom.java
  post/src/main/java/com/oing/repository/CommentRepositoryCustomImpl.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/repository/ReactionRepository.java
  post/src/main/java/com/oing/repository/ReactionRepositoryCustom.java
  post/src/main/java/com/oing/repository/ReactionRepositoryCustomImpl.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/service/CommentService.java
  post/src/main/java/com/oing/service/PostService.java
  post/src/main/java/com/oing/service/ReactionService.java
Labels: ✨ FEATURE, 🔒 HOLD, ✅ TEST, 우선순위_2

#248 [OING-329] refactor: 미션 검증 로직 중에서 가족 구성원 수 계산할 때, 어제 날짜 기준으로 세도록 수정
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/PostApiTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/service/PostService.java
  post/src/test/java/com/oing/service/PostServiceTest.java
Labels: ♻️ REFACTORING, 우선순위_3

#249 [OING-326] feat: 일일 미션 배치 구현 및 테스트코드 추가
  .github/workflows/dev-cicd.yaml
  .github/workflows/prod-cicd.yaml
  common/src/main/java/com/oing/exception/ErrorCode.java
  gateway/src/test/java/com/oing/job/DailyMissionJobTest.java
  gateway/src/test/java/com/oing/repository/DailyMissionHistoryRepositoryTest.java
  gateway/src/test/java/com/oing/repository/MissionRepositoryTest.java
  mission/src/main/java/com/oing/exception/DuplicatedDailyMissionHistoryException.java
  mission/src/main/java/com/oing/job/DailyMissionJob.java
  mission/src/main/java/com/oing/repository/DailyMissionHistoryRepository.java
  mission/src/main/java/com/oing/repository/DailyMissionHistoryRepositoryCustom.java
  mission/src/main/java/com/oing/repository/DailyMissionHistoryRepositoryCustomImpl.java
  mission/src/main/java/com/oing/repository/MissionRepository.java
  mission/src/main/java/com/oing/service/DailyMissionHistoryService.java
  mission/src/main/java/com/oing/service/MissionService.java
  mission/src/test/java/com/oing/service/DailyMissionHistoryServiceTest.java
Labels: ✨ FEATURE, ✅ TEST, 우선순위_3

#252 [OING-332] fix: getMissionByMissionId에 입력 파라미터에 @PathVariable 누락 해결
  mission/src/main/java/com/oing/restapi/MissionApi.java
Labels: 🔥 HOTFIX, 🐛 BUG, 우선순위_1

#250 [OING-330] feat: 가족 구성원 랭킹에서 '지난 날 생존신고 보기'에 대한 보충 정책 반영
  gateway/src/main/java/com/oing/controller/MainViewController.java
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/main/resources/db/migration/V202405092310__add_createdAt_idx_in_post_tbl.sql
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/MainViewApiTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/restapi/PostApi.java
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, ✅ TEST, 우선순위_3

#255 [OING-333] feature: 탈퇴한 회원 정보 값으로 "UNKNOWN"이 아닌 null 값을 주도록 수정
  gateway/src/main/java/com/oing/controller/MainViewController.java
Labels: ✨ FEATURE, 우선순위_1

#256 [OING-334] feat: 월간 캘린더 썸네일을 일간 캘린더와의 통일성을 위해 가장 먼저 올린 사진으로 변경
  build.gradle
  gateway/src/main/java/com/oing/component/SentryGateway.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/repository/PostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, 우선순위_1

#257 [OING-335] fix: 가족구성원 랭킹 API의 생존신고 수가 미션 수를 포함하는 현상 해결
  gateway/src/main/java/com/oing/repository/PostRepositoryCustomImpl.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/repository/PostRepositoryCustom.java
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, 🐛 BUG, ♻️ REFACTORING, 우선순위_2

#258 [OING-336] feat: 푸쉬 알림 메세지 변경 및 미션 업로드 시 노티 발송
  gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java
  member/src/main/java/com/oing/controller/MemberController.java
  post/src/main/java/com/oing/service/PostService.java
Labels: ✨ FEATURE, 우선순위_2
