Repository depromeet/14th-team5-BE, pull requests merged in 2024-01, with the labels that each got.

#62 [OING-107] 임시 토큰 통한 회원가입 불가 이슈 해결
  gateway/src/main/resources/application.yaml
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#63 [OING-108] feature: 응답값 없는 Operation의 기본 응답값 추가
  common/src/main/java/com/oing/dto/response/DefaultResponse.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  post/src/main/java/com/oing/controller/PostReactionController.java
  post/src/main/java/com/oing/restapi/PostReactionApi.java
Labels: ✨ FEATURE

#64 [OING-109] feat: Member, MemberPost 엔티티에 imageKey 필드 추가
  common/src/main/java/com/oing/util/PreSignedUrlGenerator.java
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
  gateway/src/main/resources/db/migration/V202401021925__add_imgKey_column.sql
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/model/Member.java
  member/src/test/java/com/oing/domain/model/MemberTest.java
  member/src/test/java/com/oing/domain/model/SocialMemberTest.java
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/domain/model/MemberPost.java
  post/src/main/java/com/oing/dto/response/PostResponse.java
  post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
  post/src/test/java/com/oing/domain/model/MemberPostTest.java
Labels: ✨ FEATURE

#65 [OING-111] 새로운 형태의 Object storage url으로 인해 썸네일 url이 작동하지 못한 오류 해결
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#66 [OING-112] feat: 딥링크 API & 딥링크 가족 가입 API 구현
  common/src/main/java/com/oing/domain/SerializableDeepLink.java
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  common/src/main/java/com/oing/exception/LinkNotValidException.java
  common/src/main/java/com/oing/service/DeepLinkDetailService.java
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/domain/model/FamilyInviteLink.java
  family/src/main/java/com/oing/exception/AlreadyInFamilyException.java
  family/src/main/java/com/oing/repository/FamilyInviteLinkRepository.java
  family/src/main/java/com/oing/restapi/FamilyApi.java
  family/src/main/java/com/oing/service/FamilyInviteLinkService.java
  gateway/src/main/java/com/oing/controller/DeepLinkController.java
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/domain/DeepLink.java
  gateway/src/main/java/com/oing/domain/DeepLinkType.java
  gateway/src/main/java/com/oing/dto/request/JoinFamilyRequest.java
  gateway/src/main/java/com/oing/dto/response/DeepLinkResponse.java
  gateway/src/main/java/com/oing/repository/DeepLinkRepository.java
  gateway/src/main/java/com/oing/restapi/DeepLinkApi.java
  gateway/src/main/java/com/oing/restapi/MeApi.java
  gateway/src/main/java/com/oing/service/DeepLinkService.java
  gateway/src/main/resources/db/migration/V202401031101__add_deep_link_tbl.sql
  member/src/main/java/com/oing/domain/model/Member.java
Labels: ✨ FEATURE

#67 [OING-113] refactor: 게시물 반응 전체 조회 응답 형식 수정
  post/src/main/java/com/oing/controller/PostReactionController.java
  post/src/main/java/com/oing/domain/Emoji.java
  post/src/main/java/com/oing/dto/response/PostReactionResponse.java
  post/src/main/java/com/oing/dto/response/PostReactionsResponse.java
  post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
  post/src/main/java/com/oing/restapi/PostReactionApi.java
  post/src/main/java/com/oing/service/PostReactionService.java
Labels: ♻️ REFACTORING

#68 [OING-115] feat: 프로덕션용 설정 및 앱 키 기능 추가
  build.gradle
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  common/src/main/java/com/oing/util/RandomStringGenerator.java
  gateway/build.gradle
  gateway/src/main/java/com/oing/ServerApplication.java
  gateway/src/main/java/com/oing/component/AppVersionCache.java
  gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
  gateway/src/main/java/com/oing/config/SpringSecurityConfig.java
  gateway/src/main/java/com/oing/config/SpringWebConfig.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/config/filter/AppVersionFilter.java
  gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  gateway/src/main/java/com/oing/config/properties/WebHeaderNameProperties.java
  gateway/src/main/java/com/oing/config/properties/WebProperties.java
  gateway/src/main/java/com/oing/domain/AppVersion.java
  gateway/src/main/java/com/oing/repository/AppVersionRepository.java
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application.yaml
  gateway/src/main/resources/banner.txt
Labels: ✨ FEATURE, 🔒 HOLD

#69 [OING-120] hotfix: 내 가족만 게시물 조회 가능하게 & 앱 키 스웨거 추가
  gateway/src/main/java/com/oing/config/SwaggerConfig.java
  gateway/src/main/java/com/oing/config/filter/AppVersionFilter.java
  gateway/src/main/java/com/oing/config/properties/WebProperties.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  gateway/src/main/resources/application.yaml
  post/src/main/java/com/oing/controller/PostController.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#70 [OING-118] hotfix: 기회원가입자 재회원가입 방지
  common/src/main/java/com/oing/domain/exception/ErrorCode.java
  gateway/src/main/java/com/oing/config/properties/WebHeaderNameProperties.java
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/exception/MemberAlreadyExistsException.java
Labels: 🔥 HOTFIX, 🐛 BUG

#73 [OING-122] hotfix: post 등록 시, 내용 길이 검증 수정
  post/src/main/java/com/oing/domain/model/MemberPost.java
Labels: 🔥 HOTFIX, 🐛 BUG

#75 [OING-124] hotfix: 리프레시 api 작동 안함 해결
  gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
Labels: 🔥 HOTFIX, 🐛 BUG

#74 [OING-123] hotfix: 새로운 형태의 Object storage url으로 인해 이미지 키가 제대로 추출되지 않는 오류 해결
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#76 [OING-125] hotfix: 유효하지 않은 토큰에 대해 401 예외 반환하는 핸들러 추가
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
Labels: 🔥 HOTFIX, 🐛 BUG

#77 [OING-125] hotfix: PR76 핫픽스
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
Labels: 🔥 HOTFIX, 🐛 BUG

#78 [OING-125] hotfix: PR76 핫픽스 2
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
Labels: 🔥 HOTFIX, 🐛 BUG

#79 [OING-127] feat: 구글 oAuth 추가
  README.md
  build.gradle
  gateway/src/main/java/com/oing/config/SpringWebConfig.java
  gateway/src/main/resources/application.yaml
  member/src/main/java/com/oing/domain/SocialLoginProvider.java
  member/src/main/java/com/oing/dto/response/GoogleAuthResponse.java
  member/src/main/java/com/oing/service/AuthService.java
Labels: ✨ FEATURE

#80 [OING-128] refactor: 가족 멤버 프로필 조회 시, 탈퇴한 회원은 응답에서 제외되도록 수정
  gateway/src/test/resources/application.yaml
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/service/MemberService.java
  member/src/test/java/com/oing/domain/SocialLoginProviderTest.java
Labels: ♻️ REFACTORING

#82 [OING-129] Widget용 이미지 압축 기능 추가
  common/src/main/java/com/oing/util/OptimizedImageUrlGenerator.java
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
  gateway/src/main/java/com/oing/controller/WidgetController.java
  gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
Labels: ✨ FEATURE

#83 [OING-130] feat: postDate 컬럼 삭제 및 가족이 없는 멤버에 대해 가족 프로필 조회 시, 예외 반환 로직 추가
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  gateway/src/main/resources/db/migration/V202401082259__delete_postDate_column.sql
  member/src/main/java/com/oing/exception/FamilyNotFoundException.java
  member/src/main/java/com/oing/service/MemberService.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/domain/MemberPost.java
  post/src/main/java/com/oing/repository/MemberPostRepository.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
  post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
  post/src/test/java/com/oing/domain/model/MemberPostTest.java
Labels: ✨ FEATURE

#84 [OING-129] OING-129 의 컴파일 에러 핫픽스
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#85 [OING-129] hotfix: OING-129 PR의 핫픽스가 머지되는 중에 꼬인 에러 해결
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#86 [OING-129] OING-129 PR에서 이미지 최적화 쿼리를 변경
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: ✨ FEATURE, 🔥 HOTFIX

#87 [OING-131] 위젯 응답 객체에 게시자 이름 추가
  gateway/src/main/java/com/oing/controller/WidgetController.java
  gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
Labels: ✨ FEATURE, 🔥 HOTFIX

#88 [OING-129] 이미지 최적화 빈의 NullPointerException 방지
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#81 [OING-104] test: 월간 캘린더 API 통합테스트 추가
  family/src/main/java/com/oing/domain/FamilyInviteLink.java
  gateway/src/main/java/com/oing/config/QuerydslConfig.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  gateway/src/main/resources/application-test.yaml
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  post/src/main/java/com/oing/domain/MemberPostCountDTO.java
  post/src/main/java/com/oing/domain/MemberPostDailyCalendarDTO.java
  post/src/main/java/com/oing/dto/response/CalendarResponse.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE, ✅ TEST

#90 [OING-133] hotfix: getThumbnailUrlGenerator 오타 해결
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#92 [OING-135] hotfix: 닉네임 길이 제한 조건 수정
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/CreateNewUserDTO.java
  member/src/main/java/com/oing/dto/request/UpdateMemberNameRequest.java
Labels: 🔥 HOTFIX

#95 [OING-138] hotfix: 링크 발급 관련 memberId 누락 이슈 해결
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  gateway/src/main/resources/application.yaml
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#96 [OING-139] fix: 깨진 WidgetApi의 통합테스트 고침
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
Labels: 🔥 HOTFIX, 🐛 BUG

#89 [OING-126] test: 회원 정보수정/조회/탈퇴에 대한 단위 테스트 코드 추가
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationHandler.java
  gateway/src/main/java/com/oing/controller/DeepLinkController.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryImpl.java
  gateway/src/main/resources/application.yaml
  gateway/src/main/resources/template-application-local.yaml
  member/src/main/java/com/oing/domain/Member.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
Labels: ✅ TEST

#97 [OING-142] feat: 댓글 기능 설계 & 구현 & 테스트
  common/src/main/java/com/oing/dto/response/ArrayResponse.java
  common/src/main/java/com/oing/dto/response/PaginationResponse.java
  common/src/main/java/com/oing/exception/ErrorCode.java
  common/src/main/java/com/oing/service/MemberBridge.java
  gateway/src/main/java/com/oing/service/MemberBridgeImpl.java
  gateway/src/main/resources/application-test.yaml
  gateway/src/test/java/com/oing/restapi/MemberPostCommentApiTest.java
  post/src/main/java/com/oing/controller/MemberPostCommentController.java
  post/src/main/java/com/oing/domain/MemberPost.java
  post/src/main/java/com/oing/domain/MemberPostComment.java
  post/src/main/java/com/oing/dto/request/CreatePostCommentRequest.java
  post/src/main/java/com/oing/dto/request/UpdatePostCommentRequest.java
  post/src/main/java/com/oing/dto/response/PostCommentResponse.java
  post/src/main/java/com/oing/exception/MemberPostCommentNotFoundException.java
  post/src/main/java/com/oing/repository/MemberPostCommentRepository.java
  post/src/main/java/com/oing/repository/MemberPostCommentRepositoryCustom.java
  post/src/main/java/com/oing/repository/MemberPostCommentRepositoryCustomImpl.java
  post/src/main/java/com/oing/restapi/MemberPostCommentApi.java
  post/src/main/java/com/oing/service/MemberPostCommentService.java
  post/src/main/java/com/oing/service/MemberPostService.java
  post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java
  post/src/test/java/com/oing/service/MemberPostCommentServiceTest.java
Labels: ✨ FEATURE

#98 [OING-143] feat: 회원탈퇴 이유 기능 추가
  gateway/src/main/resources/db/migration/V202401132338__create_MemberQuitReason.sql
  gateway/src/test/java/com/oing/restapi/MemberApiTest.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/MemberQuitReason.java
  member/src/main/java/com/oing/domain/MemberQuitReasonType.java
  member/src/main/java/com/oing/domain/key/MemberQuitReasonKey.java
  member/src/main/java/com/oing/dto/request/QuitMemberRequest.java
  member/src/main/java/com/oing/repository/MemberQuitReasonRepository.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/main/java/com/oing/service/MemberQuitReasonService.java
  member/src/test/java/com/oing/service/MemberQuitReasonServiceTest.java
Labels: ✨ FEATURE

#103 [OING-149] refactor: 가족 멤버 프로필 조회 응답에 생일 추가
  member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
  member/src/test/java/com/oing/dto/response/FamilyMemberProfileResponseTest.java
Labels: ♻️ REFACTORING

#102 [OING-148] feat: Post 삭제 기능 추가
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/repository/MemberPostCommentRepository.java
  post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
  post/src/main/java/com/oing/restapi/MemberPostApi.java
  post/src/main/java/com/oing/service/MemberPostCommentService.java
  post/src/main/java/com/oing/service/MemberPostReactionService.java
  post/src/main/java/com/oing/service/MemberPostService.java
  post/src/main/java/com/oing/service/event/DeleteMemberPostEvent.java
Labels: ✨ FEATURE

#101 [OING-147] feat: 리얼 이모지 테이블 클래스 및 리얼 이모지 API 틀 추가
  gateway/src/main/resources/db/migration/V202401141930__add_real_emoji_tbl.sql
  member/src/test/java/com/oing/controller/MemberControllerTest.java
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/domain/MemberPost.java
  post/src/main/java/com/oing/domain/MemberPostRealEmoji.java
  post/src/main/java/com/oing/domain/MemberRealEmoji.java
  post/src/main/java/com/oing/dto/request/CreateMyRealEmojiRequest.java
  post/src/main/java/com/oing/dto/request/PostRealEmojiRequest.java
  post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java
  post/src/main/java/com/oing/dto/response/RealEmojiResponse.java
  post/src/main/java/com/oing/dto/response/RealEmojisResponse.java
  post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java
  post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java
  post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
  post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java
  post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
  post/src/test/java/com/oing/domain/model/MemberPostTest.java
Labels: ✨ FEATURE, 🔒 HOLD

#99 [OING-144] feat: 가족 탈퇴 API 추가
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/restapi/MeApi.java
Labels: ✨ FEATURE

#104 [OING-105] feat: 캘린더 API를 위한 테스트 추가
  common/src/test/java/com/oing/QueryDslTestConfig.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/resources/application-test.yaml
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
Labels: ✅ TEST

#105 [OING-151] feat: 회원의 리얼이모지 POST/PUT API 구현
  common/src/main/java/com/oing/exception/ErrorCode.java
  common/src/main/java/com/oing/util/PreSignedUrlGenerator.java
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java
  gateway/src/test/resources/application.yaml
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/domain/MemberPost.java
  post/src/main/java/com/oing/domain/MemberRealEmoji.java
  post/src/main/java/com/oing/dto/request/UpdateMyRealEmojiRequest.java
  post/src/main/java/com/oing/dto/response/RealEmojiResponse.java
  post/src/main/java/com/oing/exception/DuplicateRealEmojiException.java
  post/src/main/java/com/oing/exception/RealEmojiNotFoundException.java
  post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java
  post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java
  post/src/main/java/com/oing/service/MemberRealEmojiService.java
  post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
Labels: ✨ FEATURE, ✅ TEST

#108 [OING-156] refactor: 이미지의 예상되지 않은 url 패턴으로 인한 OptimizedImageProvider의 런타임 예외를 방지
  common/src/main/java/com/oing/exception/StringEmptyWhiteSpaceException.java
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#100 [OING-146] feat: 현재 어플리케이션 최신버전 유무 API 추가
  gateway/src/main/java/com/oing/component/AppVersionCache.java
  gateway/src/main/java/com/oing/config/SpringWebConfig.java
  gateway/src/main/java/com/oing/config/support/AppKeyResolver.java
  gateway/src/main/java/com/oing/config/support/RequestAppKey.java
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/domain/AppVersion.java
  gateway/src/main/java/com/oing/dto/response/AppVersionResponse.java
  gateway/src/main/java/com/oing/restapi/MeApi.java
  gateway/src/main/resources/application.yaml
  gateway/src/main/resources/db/migration/V202401142002__add_isLatest_column.sql
Labels: ✨ FEATURE

#109 [OING-154] feat: 회원의 리얼이모지 조회 API 구현
  gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/dto/response/RealEmojiResponse.java
  post/src/main/java/com/oing/dto/response/RealEmojisResponse.java
  post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java
  post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java
  post/src/main/java/com/oing/service/MemberRealEmojiService.java
  post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java
  post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
Labels: ✨ FEATURE, ✅ TEST

#111 [OING-161] test: 피드 리액션 등록/삭제/남긴 멤버 조회 기능 테스트 코드 작성
  gateway/src/test/java/com/oing/restapi/MemberPostReactionApiTest.java
  post/src/main/java/com/oing/controller/MemberPostReactionController.java
  post/src/main/java/com/oing/dto/request/PostReactionRequest.java
  post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
Labels: ✅ TEST

#110 [OING-159] feat: 피드에 등록된 리얼이모지 리스트 조회 API 모킹
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java
Labels: ✨ FEATURE

#106 [OING-153] feat: 피드 리얼이모지 POST/DELETE API 구현
  common/src/main/java/com/oing/exception/ErrorCode.java
  gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java
  gateway/src/test/resources/application.yaml
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java
  post/src/main/java/com/oing/exception/RealEmojiAlreadyExistsException.java
  post/src/main/java/com/oing/exception/RegisteredRealEmojiNotFoundException.java
  post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java
  post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
  post/src/main/java/com/oing/service/MemberPostRealEmojiService.java
  post/src/main/java/com/oing/service/MemberRealEmojiService.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
Labels: ✨ FEATURE, ✅ TEST

#113 [OING-158] feat: 피드 리얼이모지 조회 API 구현
  gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java
  post/src/main/java/com/oing/controller/MemberPostReactionController.java
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/dto/response/PostReactionMemberResponse.java
  post/src/main/java/com/oing/dto/response/PostRealEmojiMemberResponse.java
  post/src/main/java/com/oing/dto/response/PostRealEmojiSummaryResponse.java
  post/src/main/java/com/oing/restapi/MemberPostReactionApi.java
  post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
  post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
Labels: ✨ FEATURE, ✅ TEST

#112 [OING-162] test: Post PresignedUrl/POST/DELETE 테스트 코드 추가
  gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/test/java/com/oing/controller/MemberPostControllerTest.java
Labels: ✅ TEST

#117 [OING-165] feat: 추억캘린더 새 배너 API 설계 및 모킹
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/dto/response/BannerResponse.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
Labels: ✨ FEATURE

#118 [OING-166] feat: 위젯이 자신의 게시글도 포함하도록 정책 변경
  gateway/src/main/java/com/oing/controller/WidgetController.java
Labels: ✨ FEATURE

#119 [OING-167] chore: 고장난 SonarCloud 및 jacoco 테스트 커버리지 워크플로우 수리
  gateway/src/main/java/com/oing/dto/response/PreSignedUrlResponse.java
  gateway/src/test/java/com/oing/config/support/S3PreSignedUrlProviderTest.java
Labels: 🔒 HOLD, 🐛 BUG, ⚙️ CHORE

#121 [OING-169] hotfix: 동일한 타입의 리얼 이모지 생성했는지 검증하는 로직 수정
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java
  post/src/main/java/com/oing/service/MemberRealEmojiService.java
  post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
Labels: 🔥 HOTFIX, 🐛 BUG

#116 [OING-164] refactor: Redis 설정 및 캘린더 조회(Monthly) API 캐싱 적용
  README.md
  build.gradle
  common/src/main/java/com/oing/exception/FamilyIdNotFoundException.java
  common/src/main/java/com/oing/util/security/FamilyId.java
  common/src/main/java/com/oing/util/security/FamilyIdArgumentResolver.java
  gateway/src/main/java/com/oing/config/RedisCacheConfig.java
  gateway/src/main/java/com/oing/config/RedisConfig.java
  gateway/src/main/java/com/oing/config/SpringWebConfig.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application-test.yaml
  gateway/src/main/resources/application.yaml
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/dto/response/CalendarResponse.java
  post/src/main/java/com/oing/restapi/MemberPostApi.java
Labels: ✨ FEATURE, ⚙️ CHORE, ♻️ REFACTORING

#122 [OING-170] refactor: 게시물에 달린 리얼이모지 조회 응답에 이모지 타입 추가
  post/src/main/java/com/oing/dto/response/PostRealEmojiResponse.java
Labels: ♻️ REFACTORING

#124 [OING-171] hotfix: 포스트에 달린 리얼이모지 삭제 로직 버그 해결
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java
  post/src/main/java/com/oing/service/MemberPostRealEmojiService.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
Labels: 🔥 HOTFIX, 🐛 BUG

#125 [OING-165] 바뀐 배너 정책에 맞게 배너 API 모킹 변경
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/domain/BannerImageType.java
  gateway/src/main/java/com/oing/dto/response/BannerResponse.java
Labels: 🔥 HOTFIX, ♻️ REFACTORING

#126 [OING-172] hotfix: 회원가입 시, profileImgUrl이 있다면 이미지 키 추출해서 저장하도록 로직 수정
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  member/src/main/java/com/oing/domain/Member.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#123 [OING-105] test: Widget API 테스트 코드 추가
  gateway/src/main/resources/application-test.yaml
  gateway/src/test/java/com/oing/controller/WidgetControllerTest.java
  gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
Labels: ✨ FEATURE, ✅ TEST

#127 [OING-174] feat: 사용자 그룹 가입 일자 필드 추가
  gateway/src/main/resources/db/migration/V202401281811__add_FamilyJoinAt_column.sql
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/MemberApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostCommentApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostReactionApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java
  member/src/main/java/com/oing/domain/Member.java
  member/src/main/java/com/oing/dto/response/FamilyMemberProfileResponse.java
  member/src/main/java/com/oing/dto/response/MemberResponse.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
  member/src/test/java/com/oing/domain/model/MemberTest.java
  member/src/test/java/com/oing/domain/model/SocialMemberTest.java
  member/src/test/java/com/oing/dto/response/FamilyMemberProfileResponseTest.java
Labels: ✨ FEATURE

#128 [OING-179] refactor: SingleRecentPostWidget에 PostId 추가
  gateway/src/main/java/com/oing/controller/WidgetController.java
  gateway/src/main/java/com/oing/dto/response/SingleRecentPostWidgetResponse.java
Labels: 🔥 HOTFIX, ⚙️ CHORE, ♻️ REFACTORING

#129 [OING-179] fix: 파라미터가 잘못 사용된 SingleRecentPostWidgetResponse 생성자를 고침
  gateway/src/main/java/com/oing/controller/WidgetController.java
Labels: 🔥 HOTFIX, 🐛 BUG

#131 [OING-182] refactor: 자동 주입되는 familyId 파라미터 숨김 처리
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  post/src/main/java/com/oing/restapi/MemberPostApi.java
Labels: ♻️ REFACTORING

#130 [OING-181] feat: 캘린더 통계 API 추가
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/dto/response/FamilyMonthlyStatisticsResponse.java
  family/src/main/java/com/oing/restapi/FamilyApi.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE

#134 [OING-185] chore: Embedded Redis 포트 연결 로직 수정
  gateway/src/main/resources/application-test.yaml
  gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java
Labels: 🔒 HOLD, ⚙️ CHORE

#132 [OING-173] feat: MVP 2차 추억 캘린더 배너 구현
  .gitignore
  common/src/main/java/com/oing/event/MemberPostCommentCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostCommentDeletedEvent.java
  common/src/main/java/com/oing/event/MemberPostCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostDeletedEvent.java
  common/src/main/java/com/oing/event/MemberPostReactionCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostReactionDeletedEvent.java
  common/src/main/java/com/oing/event/MemberPostRealEmojiCreatedEvent.java
  common/src/main/java/com/oing/event/MemberPostRealEmojiDeletedEvent.java
  family/src/main/java/com/oing/domain/Family.java
  family/src/main/java/com/oing/event/FamilyScoreEventListener.java
  family/src/main/java/com/oing/repository/FamilyRepository.java
  family/src/main/java/com/oing/service/FamilyService.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/domain/BannerImageType.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/resources/db/migration/V202401271853__add_familyScore_column.sql
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/controller/WidgetControllerTest.java
  gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
  member/src/main/java/com/oing/domain/Member.java
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/service/MemberService.java
  post/src/main/java/com/oing/domain/MemberPost.java
  post/src/main/java/com/oing/domain/MemberPostComment.java
  post/src/main/java/com/oing/domain/MemberPostCommentEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostReaction.java
  post/src/main/java/com/oing/domain/MemberPostReactionEntityListener.java
  post/src/main/java/com/oing/domain/MemberPostRealEmoji.java
  post/src/main/java/com/oing/domain/MemberPostRealEmojiEntityListener.java
  post/src/main/java/com/oing/repository/MemberPostCommentRepository.java
  post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
  post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java
  post/src/main/java/com/oing/repository/MemberPostRepository.java
  post/src/main/java/com/oing/service/MemberPostCommentService.java
  post/src/main/java/com/oing/service/MemberPostReactionService.java
  post/src/main/java/com/oing/service/MemberPostRealEmojiService.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE

#136 [OING-184] chore: MicroMeter Prometheus 구현체 추가
  build.gradle
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
  gateway/src/main/resources/application-test.yaml
  gateway/src/main/resources/application.yaml
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
Labels: 🔥 HOTFIX, ⚙️ CHORE

#137 [OING-184] chore: dev와 prod 환경의 application.yml에 actuator endpoints 설정을 추가
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
Labels: 🔥 HOTFIX, ⚙️ CHORE
