Repository depromeet/14th-team5-BE, pull requests merged in 2024-02, with the labels that each got.

#139 [OING-189] hotfix: THUMBNAIL_OPTIMIZER_QUERY_STRING 오타 수정
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🔥 HOTFIX, 🐛 BUG

#148 [RELEASE] release: 사진 압축 쿼리 핫픽스, 마이너 릴리즈 1.1.3
  gateway/src/main/java/com/oing/config/support/OptimizedImageUrlProvider.java
Labels: 🚀 RELEASE

#147 [OING-190] docs: 백엔드 리드미 업데이트
  README.md
Labels: 📄 DOCS

#145 [OING-177] feat: 매일 사용자 휴대폰 FCM 노티 발송 기능 추가
  build.gradle
  common/src/main/java/com/oing/service/FCMNotificationService.java
  gateway/src/main/java/com/oing/component/ApplicationListener.java
  gateway/src/main/java/com/oing/component/FCMNotificationServiceImpl.java
  gateway/src/main/java/com/oing/component/MockFCMNotificationServiceImpl.java
  gateway/src/main/java/com/oing/component/SlackGateway.java
  gateway/src/main/java/com/oing/config/FirebaseConfig.java
  gateway/src/main/java/com/oing/domain/BulkNotificationCompletedEvent.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application.yaml
  member/src/main/java/com/oing/repository/MemberDeviceRepository.java
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/service/MemberDeviceService.java
  member/src/main/java/com/oing/service/MemberService.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: ✨ FEATURE

#138 [OING-188] fix: EmbeddedRedisConfig 로직을 이전 로직으로 롤백
  gateway/src/main/resources/application-test.yaml
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
  gateway/src/test/java/com/oing/support/EmbeddedRedisConfig.java
  member/src/test/java/com/oing/domain/model/MemberTest.java
Labels: 🔒 HOLD, ♻️ REFACTORING

#150 [OING-192] hotfix: 게시물 생성/조회에서 그룹을 탈퇴한 회원 대응 가능하도록 로직 수정
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
  gateway/src/main/resources/db/migration/V202402061321__add_familyId_column.sql
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/controller/WidgetControllerTest.java
  gateway/src/test/java/com/oing/repository/MemberPostRepositoryCustomTest.java
  gateway/src/test/java/com/oing/restapi/CalendarApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostCommentApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostReactionApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java
  gateway/src/test/java/com/oing/restapi/WidgetApiTest.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/domain/MemberPost.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
  post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
  post/src/test/java/com/oing/domain/model/MemberPostCommentTest.java
  post/src/test/java/com/oing/domain/model/MemberPostReactionTest.java
  post/src/test/java/com/oing/domain/model/MemberPostTest.java
  post/src/test/java/com/oing/service/MemberPostCommentServiceTest.java
Labels: 🔥 HOTFIX, 🐛 BUG

#149 [OING-191] hotfix: 회원가입 시에 프로필 이미지 키 추출하는 로직 수정
  gateway/src/main/java/com/oing/config/support/S3PreSignedUrlProvider.java
  member/src/main/java/com/oing/service/MemberService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#152 [OING-193] feat: 회원 리얼이모지 familyId 컬럼 추가 및 로직 수정
  gateway/src/main/resources/db/migration/V202402071837__add_familyId_column_to_MemberRealEmoji.sql
  gateway/src/test/java/com/oing/restapi/MemberPostRealEmojiApiTest.java
  gateway/src/test/java/com/oing/restapi/MemberRealEmojiApiTest.java
  member/src/main/java/com/oing/domain/Member.java
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/domain/MemberRealEmoji.java
  post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java
  post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
  post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java
  post/src/main/java/com/oing/service/MemberRealEmojiService.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
  post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
Labels: ✨ FEATURE

#151 [OING-194] feat: 회원 프로필 이미지 삭제 API 구현
  gateway/src/test/java/com/oing/restapi/MemberApiTest.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/domain/Member.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
Labels: ✨ FEATURE

#160 docs: 백엔드 README.md 업데이트
  README.md
Labels: 📄 DOCS

#161 [HOTFIX] hotfix: v1.1.4 버그 긴급 핫픽스
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
  post/src/main/java/com/oing/repository/MemberPostRepositoryCustom.java
  post/src/main/java/com/oing/service/MemberPostService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#162 [HOTFIX/1.1.5] hotfix: Hotfix v1.1.5 릴리즈
  .github/workflows/devPRTemplate.yaml
  .github/workflows/mainPRTemplate.yaml
  .github/workflows/test.yaml
  common/src/main/java/com/oing/service/FamilyScoreBridge.java
  family/src/main/java/com/oing/job/FamilyStatisticJob.java
  family/src/main/java/com/oing/repository/FamilyRepository.java
  family/src/main/java/com/oing/repository/FamilyRepositoryCustom.java
  family/src/main/java/com/oing/repository/FamilyRepositoryCustomImpl.java
  family/src/main/java/com/oing/service/FamilyService.java
  family/src/main/java/com/oing/service/FamilyTopPercentageHistoryService.java
  gateway/src/main/java/com/oing/service/FamilyScoreBridgeImpl.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
Labels: ✨ FEATURE, 🔒 HOLD, 🔥 HOTFIX, 🐛 BUG

#163 [HOTFIX/1.1.6] hotfix: Hotfix v1.1.6 릴리즈
  README.md
  member/src/main/java/com/oing/restapi/MemberApi.java
  post/src/main/java/com/oing/domain/MemberPost.java
Labels: 🔥 HOTFIX, 🐛 BUG, 🚀 RELEASE

#167 [HOTFIX/1.1.6] Hotfix/1.1.6 급하니 일단 생략
  gateway/src/main/java/com/oing/controller/MeController.java
Labels: 🔥 HOTFIX

#169 [HOTFIX/1.1.6] Hotfix/1.1.6 급하니 일단 생략 222
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/event/FamilyNotificationEventListener.java
  gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
  member/src/main/java/com/oing/controller/AuthController.java
  member/src/main/java/com/oing/restapi/AuthApi.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/restapi/MemberPostApi.java
  post/src/test/java/com/oing/controller/MemberPostControllerTest.java
Labels: 🔥 HOTFIX

#165 [OING-200] hotfix: 동시성 이슈를 해결하기 위해 비관적 락 적용
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
  gateway/src/test/java/com/oing/restapi/MemberPostApiTest.java
  post/src/main/java/com/oing/repository/MemberPostReactionRepository.java
  post/src/main/java/com/oing/repository/MemberPostRealEmojiRepository.java
  post/src/main/java/com/oing/repository/MemberRealEmojiRepository.java
  post/src/main/java/com/oing/service/MemberPostReactionService.java
Labels: 🔥 HOTFIX, 🐛 BUG

#166 [OING-201] chore: 리드미의 아키텍처 업데이트
  README.md
Labels: 📄 DOCS, ⚙️ CHORE

#164 [OING-199] chore: 자코코 테스트 커버리지 적용 범위 수정
  build.gradle
Labels: 🔒 HOLD, ⚙️ CHORE

#170 docs: 수정된 디자인으로 리드미 업데이트
  README.md
Labels: 📄 DOCS

#172 [OING-224] hotfix: 가족 통계 전체 추억 수 불일치 이슈
  gateway/src/main/java/com/oing/repository/MemberPostRepositoryCustomImpl.java
Labels: 🔥 HOTFIX

#174 [OING-228] refactor: 어드민용 베너 API 삭제
  common/src/main/java/com/oing/service/FamilyScoreBridge.java
  family/src/main/java/com/oing/service/FamilyService.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/java/com/oing/service/FamilyScoreBridgeImpl.java
Labels: ♻️ REFACTORING

#175 [OING-229] feat: Dev 용 API 추가 (Prod환경 제외)
  gateway/src/main/java/com/oing/controller/DevController.java
Labels: ✨ FEATURE, 우선순위_2

#180 [OING-206] fix: 오류가 발생한 flyway initialization sql 파일 수정
  gateway/src/main/resources/db/migration/V202402252319__alter_FamilyTopPercentageHistory_tbl.sql
Labels: 🔥 HOTFIX, 🐛 BUG

#178 [OING-243] feat: 노티 스케쥴러에도 스케쥴러 락 적용
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
Labels: ✨ FEATURE, 우선순위_2

#181 [OING-205] refact: memberId, familyId등 유효성 검증 관련 리팩터링
  common/src/main/java/com/oing/service/MemberBridge.java
  common/src/main/java/com/oing/util/AuthenticationHolder.java
  common/src/main/java/com/oing/util/security/LoginFamilyId.java
  common/src/main/java/com/oing/util/security/LoginFamilyIdArgumentResolver.java
  common/src/main/java/com/oing/util/security/LoginMemberId.java
  common/src/main/java/com/oing/util/security/LoginMemberIdArgumentResolver.java
  family/src/main/java/com/oing/controller/FamilyController.java
  family/src/main/java/com/oing/restapi/FamilyApi.java
  gateway/src/main/java/com/oing/ServerApplication.java
  gateway/src/main/java/com/oing/component/TokenAuthenticationHolder.java
  gateway/src/main/java/com/oing/config/SpringWebConfig.java
  gateway/src/main/java/com/oing/controller/CalendarController.java
  gateway/src/main/java/com/oing/controller/DeepLinkController.java
  gateway/src/main/java/com/oing/controller/MeController.java
  gateway/src/main/java/com/oing/controller/WidgetController.java
  gateway/src/main/java/com/oing/restapi/CalendarApi.java
  gateway/src/main/java/com/oing/restapi/DeepLinkApi.java
  gateway/src/main/java/com/oing/restapi/MeApi.java
  gateway/src/main/java/com/oing/restapi/WidgetApi.java
  gateway/src/main/java/com/oing/service/MemberBridgeImpl.java
  gateway/src/test/java/com/oing/controller/CalendarControllerTest.java
  gateway/src/test/java/com/oing/controller/WidgetControllerTest.java
  member/src/main/java/com/oing/controller/MemberController.java
  member/src/main/java/com/oing/repository/MemberRepository.java
  member/src/main/java/com/oing/restapi/MemberApi.java
  member/src/test/java/com/oing/controller/MemberControllerTest.java
  post/src/main/java/com/oing/controller/MemberPostCommentController.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/controller/MemberPostReactionController.java
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/restapi/MemberPostApi.java
  post/src/main/java/com/oing/restapi/MemberPostCommentApi.java
  post/src/main/java/com/oing/restapi/MemberPostReactionApi.java
  post/src/main/java/com/oing/restapi/MemberPostRealEmojiApi.java
  post/src/main/java/com/oing/restapi/MemberRealEmojiApi.java
  post/src/test/java/com/oing/controller/MemberPostCommentControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostReactionControllerTest.java
  post/src/test/java/com/oing/controller/MemberPostRealEmojiControllerTest.java
  post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
Labels: ♻️ REFACTORING, 우선순위_2

#183 [OING-208] feat: Sentry 도입 및 예외와 스케줄링 Job 추적 추가
  .github/workflows/build.yaml
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  build.gradle
  family/src/main/java/com/oing/job/FamilyStatisticJob.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  gateway/src/main/resources/application.yaml
Labels: ✨ FEATURE, ⚙️ CHORE, 우선순위_1

#185 [OING-250] feat: post 모듈 로깅 추가
  post/src/main/java/com/oing/controller/MemberPostCommentController.java
  post/src/main/java/com/oing/controller/MemberPostController.java
  post/src/main/java/com/oing/controller/MemberPostReactionController.java
  post/src/main/java/com/oing/controller/MemberPostRealEmojiController.java
  post/src/main/java/com/oing/controller/MemberRealEmojiController.java
  post/src/main/java/com/oing/restapi/MemberPostApi.java
  post/src/test/java/com/oing/controller/MemberPostControllerTest.java
  post/src/test/java/com/oing/controller/MemberRealEmojiControllerTest.java
Labels: ✨ FEATURE, 우선순위_3

#186 [OING-208] feat: Sentry 고도화
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  gateway/src/main/java/com/oing/component/SentryGateway.java
  gateway/src/main/java/com/oing/config/SpringWebExceptionHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAccessDeniedHandler.java
  gateway/src/main/java/com/oing/config/filter/JwtAuthenticationEntryPoint.java
  gateway/src/main/resources/application-dev.yaml
  gateway/src/main/resources/application-prod.yaml
  gateway/src/main/resources/application.yaml
Labels: ✨ FEATURE, ⚙️ CHORE, ♻️ REFACTORING, 우선순위_1

#188 [OING-255] feat: BE UNKNOWN ERROR 등 예외 해결
  gateway/src/main/java/com/oing/component/JWTTokenGenerator.java
  gateway/src/main/java/com/oing/config/filter/WebRequestInterceptor.java
  gateway/src/main/java/com/oing/job/DailyNotificationJob.java
  member/src/main/java/com/oing/exception/TokenExpiredException.java
Labels: ✨ FEATURE, 우선순위_2

#184 [OING-248] test: 누락된 멤버 API 통합테스트 코드 추가
  gateway/src/test/java/com/oing/restapi/MemberApiTest.java
Labels: ✅ TEST, 우선순위_4
